"""ubah default status tindak lanjut

Revision ID: 9a42c29103ce
Revises: 9cb75e7dd3ad
Create Date: 2025-10-19 13:28:57.977713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a42c29103ce'
down_revision = '9cb75e7dd3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.alter_column('tindak_lanjut_kontrak',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.alter_column('tindak_lanjut_kontrak',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
