"""create all tables

Revision ID: cfca20280b63
Revises: 
Create Date: 2025-10-19 08:18:08.592501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfca20280b63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karyawan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.Column('nup', sa.String(length=50), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=150), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('unit_kerja', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('tanggal_mulai', sa.Date(), nullable=False),
    sa.Column('tanggal_akhir_kontrak', sa.Date(), nullable=True),
    sa.Column('gaji_honorarium', sa.Integer(), nullable=True),
    sa.Column('tunjangan_tetap', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nik'),
    sa.UniqueConstraint('nup')
    )
    op.create_table('template_kontrak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_template', sa.String(length=150), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dokumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('karyawan_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('nomor_surat', sa.String(length=100), nullable=True),
    sa.Column('tanggal_upload', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['karyawan_id'], ['karyawan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dokumen')
    op.drop_table('template_kontrak')
    op.drop_table('karyawan')
    # ### end Alembic commands ###
