"""menambahkan kolom status tindak lanjut

Revision ID: e4d8e25f1938
Revises: cfca20280b63
Create Date: 2025-10-19 10:55:32.303887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d8e25f1938'
down_revision = 'cfca20280b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tindak_lanjut_kontrak', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('karyawan', schema=None) as batch_op:
        batch_op.drop_column('tindak_lanjut_kontrak')

    # ### end Alembic commands ###
